test:
  mysql41: 9307
  indices_location: "/home/ubuntu/db/sphinx/test"

development:
  mysql41: 9306

production:
  mysql41: 9306
  pid_file: "/home/deployer/rlu/shared/tmp/pids/searchd.pid"
  indices_location: "/home/deployer/rlu/shared/db/sphinx"
  configuration_file: "/home/deployer/rlu/shared/config/production.sphinx.conf"
  binlog_path: "/home/deployer/rlu/shared/log/binlog"
