test:
  mysql41: 9307
  indices_location: "/home/vagrant/db/sphinx/test"

development:
  mysql41: 9306

production:
  pid_file: "~/rlu/shared/tmp/searchd.pid"
  indices_location: "~/rlu/shared/db/sphinx"
  configuration_file: "~/rlu/shared/config/production.sphinx.conf"
  binlog_path: "~/rlu/shared/log/binlog"